version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - temperature-network
    entrypoint: ["/bin/sh", "-c", "if [ '$(uname -o 2>/dev/null || echo Windows_NT)' = 'Msys' ] || [ '$(uname -o 2>/dev/null || echo Windows_NT)' = 'GNU/Linux' ]; then ./docker-build.sh build-all && python app.py; else cmd /C docker-build.bat && python app.py; fi"]
    volumes:
      - .:/app

  # Test Service
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=testing
    depends_on:
      - api
    networks:
      - temperature-network
    profiles:
      - test
    entrypoint: ["/bin/sh", "-c", "if [ '$(uname -o 2>/dev/null || echo Windows_NT)' = 'Msys' ] || [ '$(uname -o 2>/dev/null || echo Windows_NT)' = 'GNU/Linux' ]; then ./docker-build.sh build-all && python -m pytest tests/ -v; else cmd /C docker-build.bat && python -m pytest tests/ -v; fi"]
    volumes:
      - .:/app

networks:
  temperature-network:
    driver: bridge 